# Generated by Django 3.2.8 on 2021-10-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image1', models.ImageField(upload_to='posts/img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='posts/img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='posts/img')),
                ('view_count', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('tag', models.PositiveSmallIntegerField(choices=[(0, '소분'), (1, '나눔'), (2, '완료')])),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('user_key', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='product/img')),
                ('jan', models.BooleanField(default=False)),
                ('feb', models.BooleanField(default=False)),
                ('mar', models.BooleanField(default=False)),
                ('apr', models.BooleanField(default=False)),
                ('may', models.BooleanField(default=False)),
                ('jun', models.BooleanField(default=False)),
                ('jul', models.BooleanField(default=False)),
                ('aug', models.BooleanField(default=False)),
                ('sep', models.BooleanField(default=False)),
                ('oct', models.BooleanField(default=False)),
                ('nov', models.BooleanField(default=False)),
                ('dec', models.BooleanField(default=False)),
            ],
        ),
    ]
