# Generated by Django 3.2.8 on 2021-11-10 22:54

import board.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=32)),
                ('kind_name', models.CharField(max_length=32)),
                ('rank', models.CharField(max_length=8)),
                ('unit', models.CharField(max_length=8)),
                ('date', models.CharField(max_length=16)),
                ('price', models.CharField(max_length=8)),
                ('average_price', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='product/img')),
                ('month', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, size=12)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image1', models.ImageField(upload_to=board.models.post_directory_path)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=board.models.post_directory_path)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=board.models.post_directory_path)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.PositiveSmallIntegerField(choices=[(0, '소분'), (1, '나눔'), (2, '완료')])),
                ('price', models.PositiveIntegerField(default=0)),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post')),
                ('user_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
