# Generated by Django 3.2.8 on 2021-10-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image1', models.ImageField(upload_to='posts/img')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='posts/img')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='posts/img')),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.PositiveSmallIntegerField(choices=[(0, '소분'), (1, '나눔'), (2, '완료')])),
                ('price', models.PositiveIntegerField(default=0)),
                ('user_key', models.PositiveIntegerField()),
            ],
        ),
    ]
