# Generated by Django 3.2.8 on 2021-10-14 15:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='product/img')),
                ('month', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(null=True), blank=True, size=12)),
            ],
        ),
    ]
