# Generated by Django 3.2.8 on 2021-11-12 16:33

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20211111_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.post_directory_path),
        ),
    ]
