# Generated by Django 3.2.8 on 2021-10-14 15:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_alter_productmonth_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmonth',
            name='month',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), blank=True, size=12),
        ),
    ]
