# Generated by Django 3.2.8 on 2021-11-21 14:00

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_rename_local_profile_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=32)),
                ('city', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=32)),
                ('code', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.ImageField(upload_to=board.models.post_directory_path),
        ),
    ]
