# Generated by Django 3.2.8 on 2021-10-14 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_productmonth_month'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
