# Generated by Django 3.2.8 on 2021-10-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductMonth',
            new_name='Product',
        ),
    ]
