# Generated by Django 3.2.8 on 2021-10-15 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20211014_1828'),
        ('board', '0010_rename_productmonth_product'),
    ]

    operations = [
    ]
