# Generated by Django 3.2.8 on 2021-10-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20211015_1340'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=32)),
                ('kind_name', models.CharField(max_length=32)),
                ('rank', models.CharField(max_length=8)),
                ('unit', models.CharField(max_length=8)),
                ('date', models.CharField(max_length=16)),
                ('price', models.CharField(max_length=8)),
                ('average_price', models.CharField(max_length=8)),
            ],
        ),
    ]
