# Generated by Django 3.2.8 on 2021-10-25 12:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_openapi'),
    ]

    operations = [
        migrations.AddField(
            model_name='openapi',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
