# Generated by Django 3.2.8 on 2021-11-03 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_openapi_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.post'),
        ),
    ]
