# Generated by Django 3.2.8 on 2021-11-07 15:19

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_alter_post_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image1',
            field=models.FileField(upload_to=board.models.post_directory_path),
        ),
    ]
